export default function AboutPage() {
    return (
        <div className='max-w-2xl mx-auto pt-4'>
            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nam officia nesciunt suscipit eligendi ad, veritatis illo aliquid qui. Deserunt, vitae totam fugiat rem distinctio corrupti magni delectus officia temporibus eos?
            Illo a unde ullam laboriosam reprehenderit quam, iste omnis voluptas! Doloribus, natus obcaecati! Iure beatae animi iusto sit esse nisi porro, molestiae unde aliquam numquam quam dolore! Aut, inventore laborum.
            Porro repellat iste enim, iusto fuga voluptatum alias dicta similique magni corrupti est unde voluptatem libero, soluta ducimus perspiciatis laboriosam vero eaque labore earum quaerat nemo. Porro alias facilis ab.
            Iure voluptate ut id nisi. Repellat odit, ullam aliquid vitae error tempore quasi laborum, dolor soluta similique molestiae, deleniti nostrum corrupti neque veniam corporis illum tenetur. Voluptates labore possimus nobis.
            Magni sit eveniet expedita delectus ipsum nihil illum assumenda rerum, dignissimos culpa excepturi sint incidunt pariatur tempore quibusdam minus, non a. Pariatur nemo repellat fugiat libero quibusdam assumenda? Quasi, ratione.
            Excepturi fugiat illo fugit dignissimos eius ducimus vero quidem harum obcaecati cupiditate accusamus velit animi culpa libero nemo, tempore ut sapiente? Commodi magnam eos soluta a officiis minima, fuga non?
            A, quis velit. Facilis sed natus eaque commodi mollitia nobis blanditiis voluptates, quo placeat necessitatibus libero beatae quis perferendis cupiditate laboriosam nam facere laudantium explicabo recusandae animi enim numquam. Beatae.
            Possimus distinctio itaque molestias eum reiciendis quam odio id saepe officiis. Optio necessitatibus voluptas consequuntur cum quia laudantium. Voluptas optio ducimus fugit. Minus nihil recusandae mollitia fuga? Consequatur, inventore optio.
            Doloremque nemo voluptas enim debitis hic impedit magnam maiores earum nostrum praesentium corrupti perferendis distinctio nihil, eius dicta. Perferendis saepe sed debitis officiis reiciendis corrupti veritatis pariatur amet, modi qui.
            Animi voluptates suscipit, maxime ex minima enim ut tenetur voluptatibus facilis debitis dignissimos voluptate dolorum quasi minus illum, impedit exercitationem quo non, perferendis officia. Accusantium rerum quod sed culpa quia.
            Modi quas est veritatis, non recusandae illo quibusdam suscipit, tempore velit ea quia sint cum laborum corporis dolorum repellat quisquam? Neque repellendus corporis quisquam temporibus cupiditate nobis error quod repellat.
            Esse veniam nobis tempore qui alias nesciunt voluptate, ullam eos doloribus dolor sapiente eaque est repellat reprehenderit numquam vel officia ducimus quidem ex harum odit recusandae, modi voluptas cupiditate. Sequi?
            Assumenda eveniet voluptatem eius provident optio, impedit debitis et quidem maxime facere voluptates! A voluptatum sint recusandae minima quis alias sapiente, nisi distinctio iste, assumenda accusamus et excepturi doloribus iure.
            Culpa voluptatibus laboriosam dolorem numquam nulla qui? Dicta ex, fugit assumenda placeat cum, cupiditate sunt quaerat explicabo atque, repellendus dolor provident! Accusamus corrupti, unde officiis alias dolor qui quisquam mollitia!
            Mollitia ab molestiae voluptatem quam unde corrupti praesentium fugit repellendus distinctio corporis dicta ullam exercitationem, laborum inventore aspernatur error quos veniam incidunt deserunt optio fugiat quaerat. Excepturi officia perspiciatis ad?
            Quo inventore, maxime id debitis nostrum minus veritatis exercitationem molestiae alias possimus, assumenda in. A iure porro culpa reprehenderit nulla repellat eaque voluptate corporis ipsum nisi, unde officia provident illo.
            Fugit esse laborum voluptate voluptatibus facilis aspernatur laboriosam ipsum sed, minus quisquam atque expedita quidem tempora reprehenderit consequuntur. Asperiores culpa nisi fugit soluta officiis amet aliquid. Harum similique debitis ipsa.
            Modi quae, consequuntur libero nisi eligendi assumenda provident soluta, tempore, tempora harum ullam. Placeat iste blanditiis repudiandae voluptas deleniti est quasi esse magni, quidem mollitia dolorem iusto quis necessitatibus voluptate?
            Placeat doloremque eveniet consequatur ipsum amet quia minus ut, unde nulla! Maxime, ducimus ipsum id voluptatibus tempora labore vel consequatur excepturi ad necessitatibus, qui quo, incidunt aliquid facilis a beatae.
            Aliquid consequuntur optio iste suscipit praesentium, amet libero veniam modi laboriosam facilis ipsa vero eaque ipsam magni nesciunt placeat corporis! Vel eius iure, natus debitis delectus neque amet vero quisquam.
            Assumenda, modi asperiores? Esse illum totam reprehenderit? Maxime eligendi aut aliquam sunt tempore facilis optio illum cumque debitis vel. Atque ipsa numquam nulla? Eligendi amet quod tenetur magni nam ipsa!
            Omnis ipsam libero nisi veniam molestiae, neque corrupti iusto laboriosam voluptatibus eos aut est, maiores, quibusdam soluta amet quasi sequi facere dolor in doloremque? Quis assumenda voluptas fugit cupiditate doloremque.
            Possimus excepturi inventore obcaecati quibusdam error ad ratione, ut sed soluta maiores placeat, dignissimos ea porro beatae veritatis impedit accusamus nesciunt corporis! Unde autem provident nisi, illo sit aliquid cum!
            Neque rem dolores odio. Quo nulla voluptates laborum fugiat exercitationem eligendi sed beatae? Aspernatur voluptate dolorum fuga cumque fugit enim molestiae nobis, eligendi officiis porro eius nisi delectus quasi aperiam!
            Dolorum possimus provident quidem facilis, rerum ratione adipisci voluptas accusantium eos dolore rem necessitatibus quo odio vitae quia? Expedita excepturi quisquam sint eum, nobis veritatis illum dolores mollitia culpa facere?
            Consequatur blanditiis velit maxime praesentium maiores nulla soluta, hic provident. Tempore quos modi voluptas beatae fugit mollitia vero, ad voluptates magni reprehenderit velit, ducimus exercitationem rerum? Incidunt vitae vero impedit!
            Quo a impedit dolorum eum nam tempora libero, quam, doloremque sequi, architecto eius quae voluptates qui asperiores sit rerum suscipit. Velit, hic nam nesciunt quibusdam recusandae laborum architecto nemo itaque.
            Labore sequi at ea quod nam, voluptates eum deserunt unde? Laborum, similique? Veritatis, inventore. Cupiditate soluta nostrum voluptate animi est voluptatem, culpa, quisquam porro distinctio inventore maiores modi cum vitae.
            Explicabo ad non dignissimos eius possimus, ipsum consectetur, doloremque corrupti commodi ratione accusantium tempora, facilis aliquid laudantium sapiente accusamus omnis tempore dicta ut laborum itaque nisi! Fugiat harum sapiente aperiam!
            Voluptas omnis laboriosam ipsum. Velit, aspernatur esse quia veritatis aperiam voluptatibus dolores commodi iusto, expedita cumque repellat quibusdam dolorum cum consequatur nostrum. Ducimus, sunt amet ratione minima cumque totam possimus.
            Nisi sed, molestiae ipsa perspiciatis quidem beatae quae temporibus dolores laboriosam soluta optio inventore dolore sit. Nemo, similique reprehenderit, itaque non suscipit, quae soluta corporis nulla facere veritatis recusandae impedit.
            Id officia enim magni odit quidem esse amet voluptate recusandae, qui voluptas minima ut fugit eius libero. Error nostrum consectetur aspernatur sequi iure, optio ex nemo, molestiae exercitationem nisi consequuntur!
            Rerum, laboriosam! Voluptatem enim et repellendus voluptatibus eos error cupiditate non alias, minima, commodi natus. Nobis, voluptatem? Reiciendis inventore, nam perferendis veniam dolorem doloribus alias eligendi, sapiente, eaque pariatur repudiandae.
            Fugit eligendi illo vitae. Saepe perferendis doloremque libero inventore veniam cupiditate eius voluptatibus magni. Modi maxime sapiente quaerat asperiores deserunt voluptatum cum odio, quod mollitia. Quaerat totam doloremque eius aspernatur!
            Iure modi aperiam sint accusantium odio iusto unde ad ex porro, quam libero officiis repellendus quos tenetur consectetur nobis omnis quo cumque dolores debitis provident obcaecati saepe aspernatur! Voluptatem, blanditiis.
            Fuga, dolor modi. Atque quod facilis nostrum excepturi laboriosam earum id dignissimos expedita nihil assumenda. In possimus itaque, at, molestiae reprehenderit adipisci consequuntur porro quos natus quaerat incidunt quidem eos!
            Voluptatem saepe nisi ex. Quod exercitationem rem rerum aperiam, dolorem eius, ea error consectetur quos magni nobis quibusdam repellendus consequatur, officia labore blanditiis fugit quia eos ipsa deleniti possimus? Ratione?
            Debitis, id. Accusamus commodi laborum nam ipsa ab animi exercitationem, a harum eius omnis, minus, voluptatibus excepturi. Eum amet aspernatur aperiam architecto saepe quo culpa, dicta vero, ullam optio cumque!
            Eum dicta hic ut architecto velit necessitatibus eaque sed sapiente odit? Quaerat amet beatae aspernatur porro incidunt. Ipsa, architecto, nihil minus, eius dicta perspiciatis tempore sed eaque ducimus optio eos!
            Soluta natus adipisci alias itaque ipsam minus unde earum facere ipsum beatae. Dolores sequi similique modi quod ea temporibus? Commodi, quia soluta explicabo ex tempora vel aliquam officia neque suscipit?
            Nisi totam necessitatibus est atque aliquid hic. Nesciunt blanditiis minima odit aliquam, id quasi possimus cupiditate eos expedita debitis molestias tempora, nemo similique illum harum quia. Quae atque nam recusandae.
            Aspernatur autem vero, atque illo impedit expedita maiores, magnam, deserunt hic itaque nam mollitia molestias? Enim placeat culpa voluptatum impedit nam sit, dolore id debitis illo nisi consequatur eveniet quam.
            Neque perferendis suscipit doloribus rem accusantium at itaque quia cupiditate cum sunt laudantium commodi aperiam error placeat maxime quidem reiciendis, hic atque adipisci mollitia rerum. Temporibus modi possimus quo quibusdam.
            Officiis autem molestias error nihil aperiam repudiandae atque consequatur necessitatibus nostrum ipsum earum adipisci amet cum corporis fugit eaque voluptatibus illum dolore aspernatur accusantium minima, accusamus, doloribus quia! Inventore, eius.
            Velit est, maxime non consequuntur delectus tempora? Dicta beatae necessitatibus fugiat, aliquam est autem quidem, dignissimos delectus laudantium corrupti perspiciatis quisquam optio adipisci cumque esse velit, praesentium magnam officiis quae!
            Harum voluptatem veniam quae quisquam itaque at, laudantium mollitia necessitatibus accusamus numquam aperiam ea eius ipsum, amet quos inventore, nisi nulla unde cumque nihil earum tenetur nam error architecto! Dolor?
            Quibusdam voluptatum iure consectetur laborum iusto eum quo aut nisi, debitis accusamus maiores, at expedita consequuntur dicta numquam necessitatibus praesentium quia! Cum nostrum minima veritatis recusandae quam facilis dolor dolorem!
            Soluta, vero veritatis. Repellat suscipit pariatur voluptatum, quasi natus quas labore odio eveniet. Neque dolores minus error quam amet nam dolorum ullam ut impedit quis illo, recusandae dicta rerum perferendis!
            Cumque voluptate laudantium veniam quaerat quidem, perferendis cum non fugit molestiae sapiente voluptatibus suscipit ratione facilis eius consectetur facere vel voluptas cupiditate quibusdam quis quasi dolores odio saepe placeat. Nulla?
            Ea cupiditate quae architecto in? Accusantium quas quia quos placeat distinctio beatae dolor, sunt possimus accusamus totam? Doloremque, ipsa atque? Officiis aliquam distinctio autem ut tempora rerum eum ea minima.
        </div>
    )
}